"""RocketRide pipeline skills: playbooks the model reads on demand.

`src/bakeoff/data/skills/` is generated by `scripts/sync_rocketride_data.py` from
rocketride-server `docs/agents/skills/` (MIT). Every subdirectory with a `SKILL.md` is a skill.
Files at the top (`MCP_TOOL_CONTRACT.md`, `README.md`) are shared: the skills link to them, and to
each other, with relative paths such as `../MCP_TOOL_CONTRACT.md`.

Progressive disclosure: `skills_prompt()` puts only names and descriptions into the system
prompt; the `load_skill` tool returns a `SKILL.md` or a reference file when the model asks.
"""

from __future__ import annotations

import functools
import posixpath
from dataclasses import dataclass
from pathlib import Path

SKILLS_DIR = Path(__file__).resolve().parents[1] / "data" / "skills"
SKILL_FILE = "SKILL.md"
SOURCE_FILE = "SOURCE.json"  # provenance written by the sync script, not skill content
_BLOCK_SCALARS = frozenset({">", "|", ">-", "|-", ">+", "|+"})


class SkillError(ValueError):
    """An unknown skill or file. The message is what the model sees."""


@dataclass(frozen=True, slots=True)
class Skill:
    """One skill: its frontmatter and the files it may read."""

    name: str
    description: str
    # Paths relative to the skill's directory as the skill text writes them: SKILL.md first,
    # then its own reference files, then the shared files ("../MCP_TOOL_CONTRACT.md").
    files: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class Bundle:
    """The loaded skills directory."""

    root: Path
    skills: dict[str, Skill]  # by name, sorted
    paths: frozenset[str]  # every readable file, POSIX path relative to `root`


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Split a Markdown text into its `---` frontmatter fields and the body.

    Parses the YAML subset skill files use, with the standard library: `key: value` lines,
    values in optional single or double quotes, and indented continuation lines, which are
    folded with spaces (also after a `>` or `|` block indicator). `#` lines are comments.
    A text without a closed frontmatter block gives `({}, text)`.
    """
    lines = text.removeprefix("﻿").replace("\r\n", "\n").split("\n")
    if lines[0].rstrip() != "---":
        return {}, text
    end = next((i for i in range(1, len(lines)) if lines[i].rstrip() == "---"), None)
    if end is None:
        return {}, text
    fields: dict[str, str] = {}
    key: str | None = None
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line[0] in " \t" and key is not None:
            fields[key] = f"{fields[key]} {line.strip()}".lstrip()
            continue
        key, sep, value = line.partition(":")
        if not sep:
            raise ValueError(f"frontmatter line is not `key: value`: {line!r}")
        key, value = key.strip(), value.strip()
        fields[key] = "" if value in _BLOCK_SCALARS else value
    return {k: _unquote(v) for k, v in fields.items()}, "\n".join(lines[end + 1 :])


def _unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
        inner = value[1:-1]
        # YAML escapes a single quote inside '...' by doubling it.
        return inner.replace("''", "'") if value[0] == "'" else inner
    return value


@functools.cache
def _load(root: Path) -> Bundle:
    files = (p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file())
    paths = frozenset(path for path in files if path != SOURCE_FILE)
    shared = sorted(f"../{p}" for p in paths if "/" not in p)
    skills: dict[str, Skill] = {}
    for skill_md in sorted(root.glob(f"*/{SKILL_FILE}")):
        folder = skill_md.parent.name
        meta, _ = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        name, description = meta.get("name", ""), meta.get("description", "")
        # The name is how the model loads it, and the folder is how skills link to each other
        # (`../<name>/...`), so they must agree.
        if name != folder or not description:
            raise ValueError(f"{skill_md}: frontmatter needs name: {folder} and a description")
        own = sorted(p.removeprefix(f"{folder}/") for p in paths if p.startswith(f"{folder}/"))
        own.remove(SKILL_FILE)
        skills[name] = Skill(name, description, (SKILL_FILE, *own, *shared))
    return Bundle(root, skills, paths)


def load_skills(root: Path | None = None) -> Bundle:
    """The skills bundle at `root` (default `SKILLS_DIR`), loaded once per directory."""
    return _load((root or SKILLS_DIR).resolve())


def skills_prompt(root: Path | None = None) -> str:
    """The system-prompt section: each skill as `name: description`, nothing else.

    Empty when there are no skills, so the prompt never points at a tool with nothing to load.
    """
    skills = load_skills(root).skills.values()
    if not skills:
        return ""
    lines = "\n".join(f"- {s.name}: {s.description}" for s in skills)
    return (
        "## Skills\n\n"
        "These RocketRide skills are step-by-step playbooks. When a task matches a skill's "
        "description, call load_skill with that name before you act on the task, then follow "
        "it. Load only the skills you need.\n\n"
        f"{lines}"
    )


def resolve(name: str, file: str | None = None, root: Path | None = None) -> str:
    """The bundle path (relative to the skills root) of a skill's `SKILL.md` or of `file`.

    `file` is read as the skill text writes it: relative to the skill's directory
    (`GATE_PROTOCOL.md`, `../MCP_TOOL_CONTRACT.md`), or else relative to the skills root
    (`rocketride-designing-pipelines/LAYER1_NODE_INDEX.json`). Only files in the bundle are
    ever returned, so no argument can reach outside it. Raises `SkillError`.
    """
    bundle = load_skills(root)
    skill = bundle.skills.get(name)
    if skill is None:
        raise SkillError(f"Unknown skill: {name!r}. Skills: {', '.join(bundle.skills) or 'none'}")
    if file is None:
        return f"{name}/{SKILL_FILE}"
    for candidate in (posixpath.join(name, file), file):
        path = posixpath.normpath(candidate)
        if path in bundle.paths:
            return path
    raise SkillError(f"Unknown file {file!r} in skill {name!r}. Files: {', '.join(skill.files)}")


def read(path: str, root: Path | None = None) -> str:
    """The text of a bundle path returned by `resolve`."""
    bundle = load_skills(root)
    if path not in bundle.paths:  # never read anything `resolve` would not return
        raise SkillError(f"Not a skill file: {path!r}")
    return (bundle.root / path).read_text(encoding="utf-8")
